### ISSUE TITLE
rsync command for downloading raw data does not work

### ISSUE THREAD

**Issue by overshiki** [drorlab/DIPS#9]
Hi,
I tried to use the command 
```
rsync -rlpt -v -z --delete --port=33444 \
rsync.rcsb.org::biounit/coordinates/divided/ ./data/DIPS/raw/pdb
```

to download the raw data, following the `README.md`. However, I encountered the error below:
```
@ERROR: Unknown module 'biounit'
rsync error: error starting client-server protocol (code 5) at main.c(1675) [Receiver=3.1.3]
```

how could I solve this? 
Thanks a lot in advance for any help or hint!

**Comment by lizhenping** [comment]
rsync -rlpt -v -z --delete --port=33444 \
rsync.rcsb.org::ftp_data/biounit/coordinates/divided/ ./DIPS/raw/pdb

**Comment by lizhenping** [comment]
> overshiki
HI，it changed file path, try this please.

rsync -rlpt -v -z --delete --port=33444 \
rsync.rcsb.org::ftp_data/biounit/coordinates/divided/ ./DIPS/raw/pdb
https://github.com/octavian-ganea/equidock_public

**Comment by overshiki** [comment]
Hi @zhenpingli 
Cool, thanks! This new link indeed works!
